/*
 * 
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package oop.project.main;
import javax.swing.ImageIcon;
import javax.swing.text.DefaultCaret;
import oop.project.libs.*;
import oop.project.lots.*;

/**
 *
 * @author Miggy Olalo
 */
public class Main extends javax.swing.JFrame {
    static Real_Estate RE;
    static LotFrame lf;
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
        initProj();
        this.setIconImage(new ImageIcon(getClass().getResource("/house_icon.png")).getImage());
        lf = new LotFrame();
    }
    
    public void initProj(){
        RE = new Real_Estate();
        GenerateData d = new GenerateData();
        RE = d.simpleGenerate();
        ((DefaultCaret)jTextArea1.getCaret()).setUpdatePolicy(DefaultCaret.NEVER_UPDATE);
        
        
        if (RE.getBlocks().size() == 0)
                return;
        refreshBlock();
        refreshLot(false);
    }

    public void refreshLot(boolean fromCheckbox){
        int temp = cbox_addLot.getSelectedIndex();
        Block b = RE.getBlock(cbox_addBlock.getSelectedIndex());
        cbox_addLot.setModel(new javax.swing.DefaultComboBoxModel<>(b.toArray()));
        if (temp != -1 && !fromCheckbox && temp < b.getLots().size() ){
            cbox_addLot.setSelectedIndex(temp);
        }
    }

    public void refreshBlock(){
        int temp = cbox_addBlock.getSelectedIndex();
        cbox_addBlock.setModel(new javax.swing.DefaultComboBoxModel<>(RE.toArray()));
        if (temp != -1 && temp < RE.getBlocks().size()){
            cbox_addBlock.setSelectedIndex(temp);
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtarea_report = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        btn_addBlock = new javax.swing.JButton();
        cbox_addBlock = new javax.swing.JComboBox<>();
        cbox_addLot = new javax.swing.JComboBox<>();
        btn_addLot = new javax.swing.JButton();
        btn_removeBlock = new javax.swing.JButton();
        btn_generteReport = new javax.swing.JButton();
        btn_removeLot = new javax.swing.JButton();
        btn_editLot = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Real Estate");
        setPreferredSize(new java.awt.Dimension(800, 650));
        setResizable(false);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setFocusable(false);
        jTextArea1.setMaximumSize(new java.awt.Dimension(232, 84));
        jTextArea1.setMinimumSize(new java.awt.Dimension(232, 84));
        jTextArea1.setName(""); // NOI18N
        jTextArea1.setRequestFocusEnabled(false);
        txtarea_report.setViewportView(jTextArea1);

        btn_addBlock.setText("Add");
        btn_addBlock.setBorderPainted(false);
        btn_addBlock.setFocusable(false);
        btn_addBlock.setPreferredSize(new java.awt.Dimension(75, 50));
        btn_addBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addBlockActionPerformed(evt);
            }
        });

        cbox_addBlock.setPreferredSize(new java.awt.Dimension(75, 50));
        cbox_addBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_addBlockActionPerformed(evt);
            }
        });

        cbox_addLot.setPreferredSize(new java.awt.Dimension(75, 50));
        cbox_addLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbox_addLotActionPerformed(evt);
            }
        });

        btn_addLot.setText("Add");
        btn_addLot.setPreferredSize(new java.awt.Dimension(75, 50));
        btn_addLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_addLotActionPerformed(evt);
            }
        });

        btn_removeBlock.setText("Remove");
        btn_removeBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeBlockActionPerformed(evt);
            }
        });

        btn_generteReport.setText("Generate Report");
        btn_generteReport.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_generteReportActionPerformed(evt);
            }
        });

        btn_removeLot.setText("Remove");
        btn_removeLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_removeLotActionPerformed(evt);
            }
        });

        btn_editLot.setText("Edit");
        btn_editLot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_editLotActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cbox_addBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_addBlock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_removeBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_removeLot, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_addLot, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btn_editLot)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_generteReport, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbox_addLot, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtarea_report, javax.swing.GroupLayout.DEFAULT_SIZE, 394, Short.MAX_VALUE)
                .addGap(12, 12, 12))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbox_addLot, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbox_addBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_addBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_addLot, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_removeLot)
                    .addComponent(btn_removeBlock))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_editLot)
                .addGap(30, 30, 30)
                .addComponent(btn_generteReport, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addComponent(txtarea_report, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_addBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addBlockActionPerformed
        // TODO add your handling code here:
        RE.addBlock(new Block());
        // cbox_addBlock.setModel(new javax.swing.DefaultComboBoxModel<>(RE.toArray()));
        refreshBlock();
    }//GEN-LAST:event_btn_addBlockActionPerformed

    private void btn_addLotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_addLotActionPerformed
        // TODO add your handling code here:
        Block b = RE.getBlock(cbox_addBlock.getSelectedIndex());
        b.addLot(new LotFactory().createLot(-1, cbox_addBlock.getSelectedIndex())); //default
//        cbox_addLot.setModel(new javax.swing.DefaultComboBoxModel<>(b.toArray()));
        refreshLot(false);
    }//GEN-LAST:event_btn_addLotActionPerformed

    private void btn_editLotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_editLotActionPerformed
        // TODO add your handling code here:
        int blockIndex = cbox_addBlock.getSelectedIndex();
        Lot o = RE.getBlock(blockIndex).getLot(cbox_addLot.getSelectedIndex());
        lf.setLot(o, cbox_addLot.getSelectedIndex());
        lf.setVisible(true);
//        
//        lf.getLotPanel()
    }//GEN-LAST:event_btn_editLotActionPerformed

    private void cbox_addLotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_addLotActionPerformed
        // TODO add your handling code here:x`

    }//GEN-LAST:event_cbox_addLotActionPerformed

    private void cbox_addBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbox_addBlockActionPerformed
        // TODO add your handling code here:

        Block b = RE.getBlock(cbox_addBlock.getSelectedIndex());

//        cbox_addLot.setModel(new javax.swing.DefaultComboBoxModel<>(b.toArray()));
        refreshLot(true);
    }//GEN-LAST:event_cbox_addBlockActionPerformed

    private void btn_generteReportActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_generteReportActionPerformed
        // TODO add your handling code here:
        jTextArea1.setText(RE.generateReport());
    }//GEN-LAST:event_btn_generteReportActionPerformed

    private void btn_removeBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeBlockActionPerformed
        // TODO add your handling code here:
        if(cbox_addBlock.getSelectedIndex() == -1) // cannot delete when empty
            return;
        RE.removeBlock(cbox_addBlock.getSelectedIndex());
        refreshBlock();
    }//GEN-LAST:event_btn_removeBlockActionPerformed

    private void btn_removeLotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_removeLotActionPerformed
        // TODO add your handling code here:
        if(cbox_addLot.getSelectedIndex() == -1) // cannot delete when empty
            return;
        
        RE.getBlock(cbox_addBlock.getSelectedIndex()).removeLot(cbox_addLot.getSelectedIndex());
        refreshLot(false);
    }//GEN-LAST:event_btn_removeLotActionPerformed
   
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_addBlock;
    private javax.swing.JButton btn_addLot;
    private javax.swing.JButton btn_editLot;
    private javax.swing.JButton btn_generteReport;
    private javax.swing.JButton btn_removeBlock;
    private javax.swing.JButton btn_removeLot;
    private javax.swing.JComboBox<String> cbox_addBlock;
    private javax.swing.JComboBox<String> cbox_addLot;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JScrollPane txtarea_report;
    // End of variables declaration//GEN-END:variables
}
